import { StyleSheet } from "react-native";
import { brand } from "@gp/shared";

const c = brand.colors;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: c.surface },
  header: { backgroundColor: c.primary, padding: 18, gap: 12 },
  langs: { flexDirection: "row", gap: 6, alignSelf: "flex-end" },
  lang: { borderWidth: 1, borderColor: c.onPrimary, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, opacity: 0.7 },
  langActive: { backgroundColor: c.onPrimary, opacity: 1 },
  langText: { color: c.onPrimary, fontWeight: "700", fontSize: 12 },
  langTextActive: { color: c.primary },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  logo: { width: 40, height: 40, borderRadius: 10 },
  hello: { color: c.onPrimary, fontSize: 24, fontWeight: "800" },
  body: { padding: 16, gap: 12 },
  label: { fontSize: 12, letterSpacing: 1, textTransform: "uppercase", color: c.muted, fontWeight: "600" },
  muted: { color: c.muted, fontSize: 14 },
  error: { color: c.bad, fontSize: 15, fontWeight: "600" },
  title: { fontSize: 20, fontWeight: "700", color: c.text },
  back: { fontSize: 16, fontWeight: "600", color: c.primary },
  job: { flexDirection: "row", gap: 12, borderWidth: 1, borderColor: c.line, borderRadius: 12, padding: 14 },
  jobTime: { fontSize: 18, fontWeight: "800", color: c.text, width: 56 },
  jobName: { fontSize: 16, fontWeight: "700", color: c.text },
  pill: { fontSize: 13, fontWeight: "700", marginTop: 4 },
  clock: { backgroundColor: c.soft, borderRadius: 12, padding: 14, alignItems: "center", gap: 6 },
  clockTime: { fontSize: 36, fontWeight: "800", color: c.text, fontVariant: ["tabular-nums"] },
  button: { borderRadius: 12, paddingVertical: 14, paddingHorizontal: 16, alignItems: "center" },
  big: { alignSelf: "stretch", paddingVertical: 18 },
  primary: { backgroundColor: c.primary },
  primaryText: { color: c.onPrimary, fontWeight: "700", fontSize: 17 },
  signal: { backgroundColor: c.signal },
  signalText: { color: c.onSignal, fontWeight: "700", fontSize: 17 },
  ghost: { backgroundColor: c.soft },
  ghostText: { color: c.text, fontWeight: "700", fontSize: 16 },
  check: { flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderColor: c.line, borderRadius: 10, padding: 12 },
  box: { width: 26, height: 26, borderRadius: 7, borderWidth: 2, borderColor: c.line, alignItems: "center", justifyContent: "center" },
  boxOn: { backgroundColor: c.ok, borderColor: c.ok },
  boxMark: { color: c.onPrimary, fontWeight: "800" },
  checkText: { fontSize: 16, color: c.text, flex: 1 },
  checkTextOn: { color: c.muted, textDecorationLine: "line-through" },
  field: { borderWidth: 1, borderColor: c.line, borderRadius: 10, padding: 12, fontSize: 16, color: c.text },
  input: { borderWidth: 1, borderColor: c.line, borderRadius: 10, padding: 12, minHeight: 80, fontSize: 16, textAlignVertical: "top" },
  info: { gap: 6 },
  row: { flexDirection: "row", gap: 8 },
  chip: { flex: 1, borderWidth: 2, borderColor: c.line, borderRadius: 10, paddingVertical: 10, alignItems: "center" },
  chipOn: { borderColor: c.primary, backgroundColor: c.soft },
  chipText: { color: c.text, fontWeight: "700", fontSize: 15 },
  thumb: { width: 72, height: 72, borderRadius: 8, backgroundColor: c.soft },
  thumbRemove: { position: "absolute", top: -6, right: -6, width: 24, height: 24, borderRadius: 12, backgroundColor: c.text, alignItems: "center", justifyContent: "center" },
  thumbRemoveText: { color: c.surface, fontWeight: "800" },
  toast: { position: "absolute", left: 16, right: 16, bottom: 32, backgroundColor: c.text, borderRadius: 12, padding: 14 },
  toastText: { color: c.surface, fontWeight: "600", textAlign: "center" },
  scanner: { flex: 1, backgroundColor: c.text },
  scannerBar: { position: "absolute", left: 16, right: 16, bottom: 32, gap: 12 },
  scannerHint: { color: c.onPrimary, fontSize: 16, fontWeight: "600", textAlign: "center" },
});
